### ISSUE TITLE
helper_cuda.h not found when compiling with gpu support

### ISSUE THREAD

**Issue by Timarrr** [Dr-Noob/peakperf#10]
![изображение](https://user-images.githubusercontent.com/49357813/128883050-8b6bc9bd-8687-493c-b973-d5c1411f4843.png)

**Comment by Dr-Noob** [comment]
It looks like a CUDA installation issue but not related to `peakperf`. Do you have the `helper_cuda.h` file in your system? It should be in `$CUDA_HOME/samples/common/inc/`

**Comment by Timarrr** [comment]
> It looks like a CUDA installation issue but not related to `peakperf`. Do you have the `helper_cuda.h` file in your system? It should be in `$CUDA_HOME/samples/common/inc/`

I cannot find this file, even though i tried reinstalling CUDA

**Comment by Dr-Noob** [comment]
> > It looks like a CUDA installation issue but not related to `peakperf`. Do you have the `helper_cuda.h` file in your system? It should be in `$CUDA_HOME/samples/common/inc/`
> 
> I cannot find this file, even though i tried reinstalling CUDA

Hmmmm...I think that I might found the problem. From the picture you have attached, I can see that you are running Arch Linux (or any derivative). Looking at the `cuda` package in Arch, I have found that it does not include the `helper_cuda.h`, so you need to install another package, `cuda-tools`. This is clearly a bug in the `peakperf`'s `PKGBUILD` file because it only requires the package `cuda` to build `peakperf`. Can you confirm this is the issue?

**Comment by Phanty133** [comment]
I had the same issue as OP on Arch, CUDA v11.6. First installed `cuda-tools`, which created the samples directory, but just with a text file saying they've moved the samples to [a cuda-samples repo](https://github.com/NVIDIA/cuda-samples). I cloned the repo, copied the contents of the `Common` directory to `$CUDA_HOME/samples/common` and moved all `*.h` files to an `inc` subdirectory, i.e. `$CUDA_HOME/samples/common/inc`. It's not pretty, but at least it fixed it.

**Comment by Dr-Noob** [comment]
> I had the same issue as OP on Arch, CUDA v11.6. First installed `cuda-tools`, which created the `$CUDA_HOME/samples/` directory, but just with a text file saying they've moved the samples to [a cuda-samples repo](https://github.com/NVIDIA/cuda-samples). I cloned the repo, copied the contents of the `Common` directory to `$CUDA_HOME/samples/common` and moved all `*.h` files to an `inc` subdirectory, i.e. `$CUDA_HOME/samples/common/inc`. It's not pretty, but at least it fixed it.

It's not the same issue: note that CUDA v11.6 was not released when the OP posted the issue. I am aware of the issue on CUDA v11.6 and newer and will push a fix for that soon. Thanks for the remainder, tough :+1:

**Comment by Dr-Noob** [comment]
> I had the same issue as OP on Arch, CUDA v11.6. First installed `cuda-tools`, which created the `$CUDA_HOME/samples/` directory, but just with a text file saying they've moved the samples to [a cuda-samples repo](https://github.com/NVIDIA/cuda-samples). I cloned the repo, copied the contents of the `Common` directory to `$CUDA_HOME/samples/common` and moved all `*.h` files to an `inc` subdirectory, i.e. `$CUDA_HOME/samples/common/inc`. It's not pretty, but at least it fixed it.

I just pushed a fix for this problem. Probably not the most elegant solution, but it's the best way I can think of to circumvent the issue. Anyway, `peakperf` does not achieve peak performance on Ampere GPUs, this is something I still need to fix.

**Comment by Dr-Noob** [comment]
This should be fixed thanks to 3d9b73f, closing the issue.
