### ISSUE TITLE
Intel 13th Gen not is unknown

### ISSUE THREAD

**Issue by DurkJones** [Dr-Noob/peakperf#19]
Hi,
I got the following error:
Unknown microarchitecture detected: M=0x00000007 EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000001

The cpu is a 13th gen Intel I7-13700K.

If you need anything else let me know.
Dennis

**Comment by Dr-Noob** [comment]
Yes, I know that supporting Intel hybrid architecture (like Alder Lake) is not supported - it is actually at the top of my priority list, so I'd say it will come sometime in the upcoming months.

**Comment by Dr-Noob** [comment]
Hi, I have just pushed support for your CPU. 

I think it should give you 1300 GFLOP/s or more - if it doesn't please paste the output of `./peakperf --show-hybrid-topology`

**Comment by DurkJones** [comment]
Hello,

It's working now. I got 1883 GFlops.

Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
